name = "workers-test"
route = "prod-test.charliebrown.uk"

[env.staging]
route =  "stage-test.charliebrown.uk"


[env.dev]
route = "dev-test.charliebrown.uk"


[assets]
directory = "static"
binding = "ASSETS"

