name = "workers-test"
main = "src/index.js"
compatibility_date = "2023-12-01"

[env.staging]
route =  "stage-test.charliebrown.uk"


[env.dev]
route = "dev-test.charliebrown.uk"

route = "prod-test.charliebrown.uk"

[assets]
directory = "static"
binding = "ASSETS"

