name = "workers-test"
compatibility_date = "2025-07-31"
route = "prod-test.charliebrown.uk"

[env.staging]
route =  "stage-test.charliebrown.uk"


[env.dev]
route = "dev-test.charliebrown.uk"


[assets]
directory = "static"

