name = "workers-test"
main = "src/index.js"
compatibility_date = "2023-12-01"

# Production (main branch)
routes = [{ pattern = "prod-test.charliebrown.uk/*", zone_name = "charliebrown.uk" }]

[env.staging]
routes = [{ pattern = "stage-test.charliebrown.uk/*", zone_name = "charliebrown.uk" }]

[env.dev]
routes = [{ pattern = "dev-test.charliebrown.uk/*", zone_name = "charliebrown.uk" }]